name: project zjscript

on:
  schedule:
  - cron: '01 10,21,1,9 * * *' 
  workflow_dispatch:
    分支:
      - main
permissions: write-all  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create necessary directories
      run: |
        mkdir -p udpzj
        mkdir -p txt_files
        
    - name: Run main script
      run: python ${{ github.workspace }}/set/zjitems.py
         
    - name: Commit results
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain)" ]; then
          git commit -am "Automatic update"
          git push
          else
            echo "No changes detected, skipping commit."
          fi
