name: project scscript

on:
  schedule:
  - cron: '01 8,19,23,7 * * *' 
  workflow_dispatch:
    分支:
      - main
permissions: write-all  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create necessary directories
      run: |
        mkdir -p udpzj
        mkdir -p txt_files
        
    - name: Run main script
      run: python ${{ github.workspace }}/set/#scitems.py
         
    - name: Commit and push changes
      run: |
        # 配置 Git 身份
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
    
        # 同步远程变更
        git fetch origin
        git rebase origin/main
    
        # 添加并提交变更
        git add -A
        if ! git diff-index --quiet HEAD --; then
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
